### PR TITLE
Fix `Closeable.use` `NullPointerException`

### LINKED ISSUE #1450: `Closeable.use` throws NPE when `block` returns nullable
`block` return type `R` is defined as `<R>`, not `<R: Any>`. If `block` produces `null` (e.g. `Int?`) and no exception is thrown, return will cause a `KotlinNullPointerException`.

A cast as `R` instead of a double banger is needed on result

image

### PR DESCRIPTION
**Pull request by 05nelsonm**
Closes #1450

### CODE REVIEW

File: okio/src/nonWasmTest/kotlin/okio/UseTest.kt [hunk 1]
```diff
@@ -25,4 +25,11 @@ class UseTest {
 
     fakeFileSystem.checkNoOpenFiles()
   }
+
+  @Test
+  fun acceptsNullReturn() {
+    object : Closeable {
+      override fun close() {}
+    }.use { null }
```
Comment (JakeWharton) [inline okio/src/nonWasmTest/kotlin/okio/UseTest.kt:33]: Can you add an assertNull or assertEquals here just for posterity.

Comment (05nelsonm) [reply okio/src/nonWasmTest/kotlin/okio/UseTest.kt:34]: Resolved in commit f8dfad3
